Fix python 3.6 metaclass compatibility
ajtowns/beanbag pull request #10
Opened 2017-01-03 18:44 UTC by stratakis

Currently the test_sane_inheritance fail for Python 3.6

This is due to the changes done at: http://bugs.python.org/issue23722

Also some more details can be found here: https://docs.python.org/3/reference/datamodel.html#creating-the-class-object

This pull request addresses this issue for Python 3.6.

2017-01-04 11:11 UTC, stratakis commented
Also kudos to @encukou for his help with this PR

2017-08-25 19:05 UTC, gustavlarson requested changes
This change is not compiling, but after fixing them the unit tests pass on 3.6.

2017-08-25 19:05 UTC, gustavlarson commented on beanbag/namespace.py
> +        if classcell is  not None
missing : after None

2017-08-25 19:05 UTC, gustavlarson commented on beanbag/namespace.py
> +            classcell = nmspc.pop('__classcell__', None)
Initialize classcell to None before line 107

2017-09-11 11:19 UTC, stratakis commented
Thanks for taking a look at it. Made the changes you requested.

2017-09-11 15:42 UTC, gustavlarson approved these changes
Nice!

2018-01-03 18:31 UTC, ktdreyer commented on beanbag/namespace.py
> +        if classcell is  not None:
nit: two spaces in `is  not` here

2018-05-01 16:47 UTC, ktdreyer approved these changes
@ajtowns mind merging this?

2020-04-14 07:02 UTC, StykMartin reviewed
Any plans for merge? Or we can consider this project as completely dead.

2026-03-31 23:16 UTC, closed without merging